In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from datetime import datetime, timedelta
from math import log
import math

# Data Preperation

## Used DF

In [2]:
user_df = pd.read_csv(r"C:\Users\Kutay\Desktop\My Docs\My Docs v2.0\Data Science\RA\Cryptocurrency\Input\Top 20 Cryptocurrencies and Related TW Accounts.csv", encoding="ISO-8859-1")
user_df.head()

,Coin,ID,Owner/Influence,Name,Screen_name,Status,Why did I choose this person?
0,Ethereum,ethereum,Vitalik Buterin,vitalik.eth,VitalikButerin,co-founder,he is also known in crypto world
1,BNB,binancecoin,Changpeng Zhao,CZ ??Binance,cz_binance,CEO,NaN
2,XRP,ripple,Brad Garlinghouse,Brad Garlinghouse,bgarlinghouse,CEO,NaN
3,ADA(Cardano),cardano,Charles Hoskinson,Charles Hoskinson,IOHK_Charles,CEO/co-founder,NaN
4,DOGE,dogecoin,Elon Musk_doge,Elon Musk,elonmusk,influencer,"as a popular figure, highly interested in this..."

## Min-Max Day Finder

In [3]:
def last_day_finder(tweet_df):
    max_index = len(tweet_df)-1
    user = tweet_df["Screen_name"][0]
    last_day = tweet_df["Date"][0]
    for x in tweet_df.index:
        if(x != max_index):
            if(tweet_df["Screen_name"][x] != tweet_df["Screen_name"][x+1]):
                if(tweet_df["Date"][x+1] > last_day):
                    last_day = tweet_df["Date"][x+1]
                    user = tweet_df["Screen_name"][x+1]            
        elif(x == max_index):
            if(tweet_df["Date"][x] > last_day):
                last_day = tweet_df["Date"][x]
                user = tweet_df["Screen_name"][x]
    
    print("Last day of data is ", last_day, "and user who has the last tweet is", user)

In [4]:
#It finds the common oldest day between all users.
def oldest_common_day_finder(tweet_df):
    max_index = len(tweet_df)-1
    most_active_user = ""
    max_day = ""
    for x in tweet_df.index:
        if(x != max_index):
            if(tweet_df["Screen_name"][x] != tweet_df["Screen_name"][x+1]):
                if(tweet_df["Date"][x] > max_day):
                    max_day = tweet_df["Date"][x]
                    most_active_user = tweet_df["Screen_name"][x]
        elif(x == max_index):
            if(tweet_df["Date"][x] > max_day):
                max_day = tweet_df["Date"][x]
                most_active_user = tweet_df["Screen_name"][x]
    print("Oldest common day is", max_day, "and Most active user is", most_active_user)

In [5]:
tweet_df = pd.read_csv(r"C:\Users\Kutay\Desktop\My Docs\My Docs v2.0\Data Science\RA\Cryptocurrency\RA_Cryptocurrency\Data\Input Data\tweets_all.csv", encoding="ISO-8859-1")
tweet_df.drop("Unnamed: 0", inplace=True, axis=1)
oldest_common_day_finder(tweet_df)
last_day_finder(tweet_df)

Oldest common day is 2022-10-09 13:30:21 and Most active user is elonmusk
Last day of data is  2022-12-31 23:41:41 and user who has the last tweet is VitalikButerin

In [6]:
#add 1 to max_day to ensure getting all tweets of most active user at specified day.
max_day = "2022-10-10"
last_day = "2022-12-31"
idx = pd.period_range(max_day, last_day)

## Seperator

In [7]:
def separator(index ,tweet_df):
    result = tweet_df
    result.insert(index, "Time", "", True)
    
    for x in result.index:
        date = result.loc[x]["Date"]
        result["Date"][x] = date.split(" ")[0]
        result["Time"][x] = date.split(" ")[1]
    return result

## Price Data

In [8]:
price_df = pd.read_csv(r"C:\Users\Kutay\Desktop\My Docs\My Docs v2.0\Data Science\RA\Cryptocurrency\RA_Cryptocurrency\Data\Input Data\price_data_v2.csv")
price_df.drop("Unnamed: 0", inplace=True, axis=1)
price_df.rename(columns={"date_time": "Date"}, inplace=True)
price_df = separator(4, price_df)
price_df.drop("Time", inplace=True, axis=1)
price_df_v2 = price_df[price_df["Date"] >= max_day]
price_df_v2.reset_index(inplace = True, drop = True)
price_df_v2

<ipython-input-7-0383d5a971fa>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result["Date"][x] = date.split(" ")[0]
<ipython-input-7-0383d5a971fa>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result["Time"][x] = date.split(" ")[1]

,day,ID,timestamps,Date,price,market_caps,volumes,price_dif,%change,st_dev,>st_dev
0,318,ethereum,1665360000000,2022-10-10,1322.269755,1.595863e+11,4.753165e+09,6.411955,0.004873,0.047117,0
1,319,ethereum,1665446400000,2022-10-11,1291.081660,1.561804e+11,7.492362e+09,-31.188096,-0.023587,0.047093,0
2,320,ethereum,1665532800000,2022-10-12,1279.883308,1.546575e+11,8.314705e+09,-11.198352,-0.008674,0.047071,0
3,321,ethereum,1665619200000,2022-10-13,1294.271051,1.564886e+11,7.512521e+09,14.387744,0.011241,0.047072,0
4,322,ethereum,1665705600000,2022-10-14,1288.164015,1.557033e+11,1.537497e+10,-6.107037,-0.004719,0.047072,0
...,...,...,...,...,...,...,...,...,...,...,...
1323,396,cosmos,1672099200000,2022-12-27,9.165806,2.685435e+09,7.984043e+07,0.140715,0.015592,0.056996,0
1324,397,cosmos,1672185600000,2022-12-28,9.217066,2.692638e+09,9.948979e+07,0.051261,0.005593,0.057004,0
1325,398,cosmos,1672272000000,2022-12-29,9.121968,2.670882e+09,1.163803e+08,-0.095098,-0.010318,0.056722,0
1326,399,cosmos,1672358400000,2022-12-30,9.342944,2.736200e+09,1.141521e+08,0.220976,0.024225,0.056503,0
1327,400,cosmos,1672444800000,2022-12-31,9.366087,2.740644e+09,1.000293e+08,0.023143,0.002477,0.056384,0

## Tweet Data

In [9]:
tweet_df.reset_index(inplace = True, drop = True)
tweet_df = separator(6, tweet_df)
tweet_df_clean = tweet_df
tweet_df_v2 = tweet_df[tweet_df["Date"] >= max_day]
tweet_df_v2.head()

<ipython-input-7-0383d5a971fa>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result["Date"][x] = date.split(" ")[0]
<ipython-input-7-0383d5a971fa>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result["Time"][x] = date.split(" ")[1]

,Tweet_id,Name,Screen_name,Related_coin,Tweet,Date,Time,Category,N_of_RT,N_of_fav,Day,Month,Year
0,1.609330e+18,vitalik.eth,VitalikButerin,ethereum,@ChenWainuo @zengjiajun_eth @BlockGeekDima ???...,2022-12-31,23:41:41,reply,3,11,31,12,2022
1,1.609310e+18,vitalik.eth,VitalikButerin,ethereum,RT @VitalikButerin: @IAPonomarenko Happy new y...,2022-12-31,22:15:52,retweet,648,0,31,12,2022
2,1.609310e+18,vitalik.eth,VitalikButerin,ethereum,"@IAPonomarenko Happy new year, and lots of lov...",2022-12-31,22:06:42,reply,648,5682,31,12,2022
3,1.609220e+18,vitalik.eth,VitalikButerin,ethereum,@lexfridman @GretaThunberg @Cobratate I would ...,2022-12-31,15:49:58,reply,169,4965,31,12,2022
4,1.609210e+18,vitalik.eth,VitalikButerin,ethereum,"@balajis Reaching the ""basic rollup scaling"" m...",2022-12-31,15:27:04,reply,453,2807,31,12,2022

In [10]:
"""#Groupby
tweet_counts = tweet_df_v2.sort_values(["Related_coin", "Date"], ascending=True).groupby(["Related_coin", "Date"], sort=False)["Tweet_id"].count()
tw_count_df = tweet_counts.to_frame()
tw_count_df.rename(columns={"Tweet_id": "Num_Tweets"}, inplace=True)
tw_count_df
#Reindex
(coin_index, date_index) = tw_count_df.index.levels
new_index = pd.MultiIndex.from_product([coin_index, a], names=["Related_coin", "Date"])
tw_count_df_v2 = tw_count_df.reindex(new_index)
tw_count_df_v2["LN"] = np.where(tw_count_df_v2['Num_Tweets']>0, np.log(tw_count_df_v2['Num_Tweets']), 0)
tw_count_df_v2"""

'#Groupby\ntweet_counts = tweet_df_v2.sort_values(["Related_coin", "Date"], ascending=True).groupby(["Related_coin", "Date"], sort=False)["Tweet_id"].count()\ntw_count_df = tweet_counts.to_frame()\ntw_count_df.rename(columns={"Tweet_id": "Num_Tweets"}, inplace=True)\ntw_count_df\n#Reindex\n(coin_index, date_index) = tw_count_df.index.levels\nnew_index = pd.MultiIndex.from_product([coin_index, a], names=["Related_coin", "Date"])\ntw_count_df_v2 = tw_count_df.reindex(new_index)\ntw_count_df_v2["LN"] = np.where(tw_count_df_v2[\'Num_Tweets\']>0, np.log(tw_count_df_v2[\'Num_Tweets\']), 0)\ntw_count_df_v2'

In [12]:
#Groupby
tweet_counts = tweet_df_v2.sort_values(["Related_coin", "Date"], ascending=True).groupby(["Related_coin", "Date"], sort=False)["Tweet_id"].count()
tw_count_df = tweet_counts.to_frame()
tw_count_df.rename(columns={"Tweet_id": "Num_Tweets"}, inplace=True)

#Reindex
(coin_index, date_index) = tw_count_df.index.levels
new_index = pd.MultiIndex.from_product([coin_index, date_index], names=["Related_coin", "Date"])
tw_count_df = tw_count_df.reindex(new_index)
tw_count_df = tw_count_df.fillna(0).astype(int)
tw_count_df["LN"] = np.where(tw_count_df['Num_Tweets']>0, np.log(tw_count_df['Num_Tweets']), 0)
tw_count_df

C:\Users\Kutay\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

                         Num_Tweets        LN
Related_coin Date
avalanche-2  2022-10-10           3  1.098612
             2022-10-11          18  2.890372
             2022-10-12           4  1.386294
             2022-10-13           2  0.693147
             2022-10-14           1  0.000000
...                             ...       ...
uniswap      2022-12-18           0  0.000000
             2022-12-24           0  0.000000
             2022-12-28           1  0.000000
             2022-12-30           1  0.000000
             2022-12-31           0  0.000000

[1328 rows x 2 columns]

In [13]:
a = pd.period_range(start='2022-10-10', end='2022-12-31', freq='D')

# Linear Regression

In [14]:
a = price_df[price_df["ID"] == "avalanche-2"]["%change"].tolist()

In [15]:
b = var_y = tw_count_df["LN"]["avalanche-2"].tolist()

In [16]:
def variance(data, n, ddof=0): #ddof = 0 for population, =1 for sample variance 
    if(n != 0):
        mean = sum(data) / n
        return sum((x - mean) ** 2 for x in data) / (n - ddof)
    else:
        return 144

In [17]:
def std_err_calculator(data):
    n = len(data)
    var = variance(data, n)
    std_dev = math.sqrt(var)
    std_err = std_dev/math.sqrt(n)
    return std_err

## Common Day

In [18]:
def common_day_linearRegression(user_df, price_df_v2, tw_count_df):
    columns = ["ID", "Screen_name", "R_sq", "Intercept", "coef", "t_stat"]
    data = []
        
    for x in user_df.index:
        coin_id = user_df["ID"][x]
        user = user_df["Screen_name"][x]
        
        #independent
        var_x = price_df_v2[price_df_v2["ID"] == coin_id]["%change"].tolist()
        var_x = np.reshape(var_x, (-1,1))
        
        #dependent
        var_y = tw_count_df["LN"][coin_id].tolist()
        std_err = std_err_calculator(var_y) #standart error calculation
        var_y = np.reshape(var_y, [1, len(var_y)])[0]
        model = LinearRegression().fit(var_x, var_y)
        t_stat = model.coef_[0]/std_err
        
        
        data.append([coin_id, user, model.score(var_x, var_y), model.intercept_, model.coef_[0], t_stat])
    
    return pd.DataFrame(data, columns = columns)

In [19]:
def different_days_linearRegression(user_df, price_df, tweet_df):
    columns = ["ID", "Screen_name", "R_sq", "Intercept", "coef", "t_stat"]
    data = []
    
    for x in user_df.index:
        coin_id = user_df["ID"][x]
        user = user_df["Screen_name"][x]
        
        #slicing
            #tweet_df
        slice_tw = tweet_df.loc[tweet_df["Screen_name"] == user]
        first_day_tw =  slice_tw["Date"].iloc[-1]
        last_day_tw = slice_tw["Date"].iloc[0]
        slice_pr = price_df.loc[tweet_df["Screen_name"] == user]
        first_day_pr =  slice_pr["Date"].iloc[-1]
        last_day_pr = slice_pr["Date"].iloc[0]
        #old days are bigger
        if(first_day_tw > first_day_pr):
            first_day = first_day_tw
        else:
            first_day = first_day_pr
            
        if(last_day_tw < last_day_pr):
            last_day = last_day_tw
        else:
            last_day = last_day_pr
            #filtering
        slice_tw = slice_tw[(slice_tw["Date"] > first_day) & (slice_tw["Date"] <= last_day)]
        slice_pr = slice_pr[(slice_pr["Date"] > first_day) & (slice_pr["Date"] <= last_day)]
        
        #tweet counts and LN
            #Groupby
        tweet_counts = slice_tw.sort_values(["Related_coin", "Date"], ascending=True).groupby(["Related_coin", "Date"], sort=False)["Tweet_id"].count()
        tw_count_df = tweet_counts.to_frame()
        tw_count_df.rename(columns={"Tweet_id": "Num_Tweets"}, inplace=True)
        print(tw_count_df)

            #Reindex
        (coin_index, date_index) = tw_count_df.index.levels
        new_index = pd.MultiIndex.from_product([coin_index, date_index], names=["Related_coin", "Date"])
        tw_count_df = tw_count_df.reindex(new_index)
        tw_count_df = tw_count_df.fillna(0).astype(int)
        tw_count_df["LN"] = np.where(tw_count_df['Num_Tweets']>0, np.log(tw_count_df['Num_Tweets']), 0)
           
        #Linear Regression
            #independent
        var_x = slice_pr[slice_pr["ID"] == coin_id]["%change"].tolist()
        var_x = np.reshape(var_x, (-1,1))
            #dependent
        var_y = tw_count_df["LN"][coin_id].tolist()
        std_err = std_err_calculator(var_y) #standart error calculation
        var_y = np.reshape(var_y, [1, len(var_y)])[0]
        model = LinearRegression().fit(var_x, var_y)
        t_stat = model.coef_[0]/std_err
        
        data.append([coin_id, user, model.score(var_x, var_y), model.intercept_, model.coef_[0], t_stat])
    
    return pd.DataFrame(data, columns = columns)

In [20]:
common_day = common_day_linearRegression(user_df, price_df_v2, tw_count_df)
common_day

               ID      Screen_name      R_sq  Intercept      coef     t_stat
0        ethereum   VitalikButerin  0.000072   1.777679  0.181044   1.789416
1     binancecoin       cz_binance  0.015518   2.632461  2.340007  28.257543
2          ripple    bgarlinghouse  0.034961   0.067540 -1.086403 -37.880161
3         cardano     IOHK_Charles  0.000081   1.970740  0.151102   2.046992
4        dogecoin         elonmusk  0.001293   3.179269 -0.276706  -4.348210
5   matic-network   sandeepnailwal  0.046596   2.720504 -2.256257 -28.170070
6        polkadot   Web3foundation  0.004208   0.172659  0.863814  16.100521
7             hex  RichardHeartWin  0.015673   1.912242 -2.408003 -23.266496
8       shiba-inu         elonmusk  0.004844   3.177043 -0.930866 -14.652747
9          solana           solana  0.000529   0.975236  0.261886   2.817064
10           tron    justinsuntron  0.017842   1.234791 -5.243976 -54.139129
11        uniswap          Uniswap  0.002708   0.647402  0.828589   9.664521
12       litecoin      SatoshiLite  0.005397   0.327932  0.795576  14.050077
13    avalanche-2       el33th4xor  0.003694   1.199584 -1.364132 -11.643805
14      chainlink    SergeyNazarov  0.027894   0.026498  0.575634  31.165577
15         cosmos      buchmanster  0.000080   1.080141 -0.193698  -1.567563

In [37]:
different_day = different_days_linearRegression(user_df, price_df, tweet_df)
different_day

                         Num_Tweets
Related_coin Date
ethereum     2021-12-06           2
             2021-12-19           1
             2022-01-01          28
             2022-01-02           1
             2022-01-03           2
...                             ...
             2022-06-11           8
             2022-06-12           4
             2022-06-13           6
             2022-06-14          10
             2022-06-15          11

[111 rows x 1 columns]

ValueError: Found input variables with inconsistent numbers of samples: [1, 111]

In [22]:
common_day.to_excel(r"C:\Users\Kutay\Desktop\My Docs\My Docs v2.0\Data Science\RA\Cryptocurrency\RA_Cryptocurrency\Data\Regression Results\regression_results_LN.xlsx")

## Different Days